- name: Create user {{username}}
  hosts: {{target_hosts}}
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Create user {{username}}
      user:
        name: {{username}}
        state: present
        shell: /bin/bash
        create_home: yes
        
    - name: Add {{username}} to sudo group (Debian/Ubuntu)
      user:
        name: {{username}}
        groups: sudo
        append: yes
      when: ansible_os_family == "Debian"
      
    - name: Add {{username}} to wheel group (RHEL/CentOS)
      user:
        name: {{username}}
        groups: wheel
        append: yes
      when: ansible_os_family == "RedHat"
      
    - name: Verify user creation
      command: id {{username}}
      register: user_check
      changed_when: false
      
    - name: Display user info
      debug:
        msg: "✓ User {{username}} created successfully on {{ ansible_distribution }}"