---
- name: Install {{package_name}} on servers
  hosts: {{target_hosts}}
  become: yes
  gather_facts: yes
  
  tasks:
    # Update package cache (Debian/Ubuntu)
    - name: Update apt cache (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
      
    # Install on Debian/Ubuntu
    - name: Install {{package_name}} on Debian/Ubuntu
      apt:
        name: {{package_name}}
        state: present
      when: ansible_os_family == "Debian"
      
    # Install on RHEL/CentOS/Rocky/Alma
    - name: Install {{package_name}} on RHEL/CentOS
      yum:
        name: {{package_name}}
        state: present
      when: ansible_os_family == "RedHat"
      
    # Install on Fedora
    - name: Install {{package_name}} on Fedora
      dnf:
        name: {{package_name}}
        state: present
      when: ansible_os_family == "Fedora"
      
    # Verify installation (works on all)
    - name: Verify {{package_name}} is installed
      command: which {{package_name}}
      register: package_check
      changed_when: false
      failed_when: false
      
    - name: Display success message
      debug:
        msg: "✓ {{package_name}} installed successfully on {{ ansible_distribution }} {{ ansible_distribution_version }}"
      when: package_check.rc == 0


