- name: Restart {{service_name}} service
  hosts: {{target_hosts}}
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Restart {{service_name}}
      service:
        name: {{service_name}}
        state: restarted
        
    - name: Wait for service to be ready
      wait_for:
        port: {{port}}
        delay: 5
        timeout: 30
      when: port is defined
      
    - name: Verify {{service_name}} is running
      service:
        name: {{service_name}}
        state: started
      register: service_status
      
    - name: Display service status
      debug:
        msg: "✓ {{service_name}} restarted successfully on {{ ansible_distribution }}"